### ISSUE TITLE
Write a script to rename raw data 

### ISSUE THREAD

**Issue by pilopilota** [fridoling/sequencing#3]
we should write a (bash?) script to rename raw data file.

illumina raw data usually are named
SampleName_S1_L001_R1_001.fastq.gz

S is sample number
L is lane
R is 1 or 2 for the two pair-end files
001 is always the end.
here's the full explanation:
https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/NamingConvention_FASTQ-files-swBS.htm

we need 
date_SampleName_R1 or date_SampleName_R2
date should be yyyymmdd

**Comment by fridoling** [comment]
I haven't included the renaming function yet, because I wasn't sure at which point it would be best to do so. Since the names are so standardized by Illumina they won't be a problem for the scripts and it would also be possible to do the renaming step only when creating the bam files. But I am ok either way.

**Comment by pilopilota** [comment]
I think it's better to rename the raw data, to have raw data and bams (and all the intermediate steps) with a unique ID (date_sample). this would help understanding the data flow.
the only data with a different name (the original), would be those in the original zipped archive they send us. I think it's fine, it is unlikely to take a look into it after unzipping

**Comment by pilopilota** [comment]
I wrote a script to rename fasta files, and pushed it to the master :)
arg! first time..I hope I did not mess up anything.
if you can check it and integrate it into main_bam_pipeline it would be great!

**Comment by fridoling** [comment]
it works great after removing the 'echo' before the mv command :)
I will now integrate it into the pipeline

**Comment by pilopilota** [comment]
hahah ops!
